### ISSUE TITLE
When I add a new camera, recording is turned on automatically. It should not.

### ISSUE THREAD

**Issue by faisal2472** [evercam/evercam-api#414] opened 2015-08-26 11:09 UTC
@mosic   I am adding  cameras in dash evercam.io without enable any recording mode . automatically start recording .

**Comment by mosic** [comment] 2015-08-28 06:06
@faisal2472 Yep, currently cameras with recording set to off do record, just at lower frequency (once a minute). This is a temporary situation, will be fixed when the cloud recording / scheduling gets ironed out. /cc @marcoherbst

**Comment by marcoherbst** [comment] 2015-08-28 07:06
So, given that 1/min is intended behaviour to tell if the camera is online
or not, we can say that Recording is NOT enabled for all new cameras. True?

In which case, close this issue @mosic . Thanks.
M

On 28 August 2015 at 07:07, Miloš Mošić <notifications@github.com> wrote:

> @faisal2472 <https://github.com/faisal2472> Yep, currently cameras with
> recording set to off do record, just at lower frequency (once a minute).
> This is a temporary situation, will be fixed when the cloud recording /
> scheduling gets ironed out. /cc @marcoherbst
> <https://github.com/marcoherbst>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-api/issues/414#issuecomment-135643455>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment] 2015-08-28 15:00
@marcoherbst Yes, exactly.

**Closed by mosic** 2015-08-28 15:00 UTC
